name: Label PRs & Issues

on:
  issues:
    types: [opened, edited]


jobs:
  auto-label-issues:
    runs-on: ubuntu-18.04
    steps:
    - name: Auto-label ROCm
      run: |
        set -eux
        TITLE="${{ github.event.issue.title }}"
        ISSUE_NUMBER=${{ github.event.issue.number }}
        OWNER="${{ github.repository_owner }}"
        REPO="${{ github.repository }}"
        if [[ ${TITLE,,} =~ *rocm* ]]; then
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$OWNER/$REPO/issues/$ISSUE_NUMBER/labels \
            -d '{"labels":["ROCm"]}'
        fi
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
